# Generated by Django 3.0.9 on 2021-10-14 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
        ('lechnerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.Supplier'),
        ),
        migrations.AlterField(
            model_name='moldingtool',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.Supplier'),
        ),
        migrations.AlterField(
            model_name='package',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lechnerapp.Material'),
        ),
        migrations.AlterField(
            model_name='package',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lechnerapp.Product'),
        ),
        migrations.AlterField(
            model_name='package',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.Supplier'),
        ),
    ]
