# Generated by Django 3.0.9 on 2021-10-15 02:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
        ('lechnerapp', '0003_package_package_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=191, null=True)),
                ('part_number', models.CharField(max_length=191, null=True)),
                ('charge_number', models.CharField(max_length=191, null=True)),
                ('date', models.DateField(null=True)),
                ('product_use_location', models.CharField(max_length=191, null=True)),
                ('ware_house', models.CharField(max_length=191, null=True)),
                ('row_number', models.IntegerField(default=0, null=True)),
                ('part_location', models.CharField(max_length=191, null=True)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lechnerapp.Product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.Supplier')),
            ],
        ),
    ]
