# Generated by Django 3.0.9 on 2021-10-12 08:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191, null=True)),
                ('legal_form', models.CharField(max_length=191, null=True)),
                ('uid', models.CharField(max_length=191, null=True)),
                ('website', models.CharField(max_length=800, null=True)),
                ('internal_number', models.CharField(max_length=191)),
                ('phone', models.CharField(max_length=191, null=True)),
                ('categories', models.CharField(max_length=191, null=True)),
                ('type', models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier')], default='supplier', max_length=40)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(null=True)),
                ('address', models.TextField(null=True)),
                ('phone', models.TextField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
