# Generated by Django 3.0.9 on 2021-09-30 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191, null=True)),
                ('legal_form', models.CharField(max_length=191, null=True)),
                ('uid', models.CharField(max_length=191, null=True)),
                ('website', models.CharField(max_length=800, null=True)),
                ('internal_number', models.CharField(max_length=191)),
                ('phone', models.CharField(max_length=191, null=True)),
                ('categories', models.CharField(max_length=191, null=True)),
                ('type', models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier')], default='supplier', max_length=40)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
